name: Angular Cordova

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g @angular/cli@10.0.4
    - name: build Angular
      run: |
        cd src
        cd saveBox
        npm i
        ng build --prod
    - name : copy new files
      run: |
        ls -lh src/saveBox/dist/saveBox/
        rm -r docs/*
        cp -r src/saveBox/dist/saveBox/* docs/
        ls -lh src/saveBox/dist/saveBox/
        
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git commit -m "adding new data" -a --allow-empty
  
                  
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name : copy to cordova
      run: |
        ls -lh src/
        echo 'src'
        ls -lh src/saveBox/Cordova/MyApplication/www/
        rm src/saveBox/Cordova/MyApplication/www/angular.html
        ls -lh src/saveBox/Cordova/MyApplication/www/
        mv src/saveBox/dist/saveBox/index.html src/saveBox/dist/saveBox/angular.html
        cp -r src/saveBox/dist/saveBox/* src/saveBox/Cordova/MyApplication/www/
        ls -lh src/saveBox/Cordova/MyApplication/www/
    
    - name: Build cordova
      shell: pwsh
      run: |
        $currentDir = (Get-Item .).FullName
        Write-Host $currentDir
        mkdir $currentDir/out
        Write-Host $currentDir
        dir $currentDir
        Push-Location $currentDir/src/saveBox/Cordova/
        &"docker" build  -f cordova.txt -t  cordovaimage .
        &"docker" run -d  --name cordovacontainer --rm cordovaimage
        &"docker" cp cordovacontainer:/app/out  $currentDir/out/
        &"docker" container kill cordovacontainer
        Pop-Location 
    - name : verify apk
      run: |
        ls -lh out/
           
    - name: artifacts      
      uses: actions/upload-artifact@v2
      with:
        name: exe ${{ env.GITHUB_REF_SLUG  }}
        path: out
